// Code generated by go-swagger; DO NOT EDIT.

package example

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetExampleHelloworldReader is a Reader for the GetExampleHelloworld structure.
type GetExampleHelloworldReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetExampleHelloworldReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetExampleHelloworldOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /example/helloworld] GetExampleHelloworld", response, response.Code())
	}
}

// NewGetExampleHelloworldOK creates a GetExampleHelloworldOK with default headers values
func NewGetExampleHelloworldOK() *GetExampleHelloworldOK {
	return &GetExampleHelloworldOK{}
}

/*
GetExampleHelloworldOK describes a response with status code 200, with default header values.

OK
*/
type GetExampleHelloworldOK struct {
	Payload string
}

// IsSuccess returns true when this get example helloworld o k response has a 2xx status code
func (o *GetExampleHelloworldOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get example helloworld o k response has a 3xx status code
func (o *GetExampleHelloworldOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get example helloworld o k response has a 4xx status code
func (o *GetExampleHelloworldOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get example helloworld o k response has a 5xx status code
func (o *GetExampleHelloworldOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get example helloworld o k response a status code equal to that given
func (o *GetExampleHelloworldOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get example helloworld o k response
func (o *GetExampleHelloworldOK) Code() int {
	return 200
}

func (o *GetExampleHelloworldOK) Error() string {
	return fmt.Sprintf("[GET /example/helloworld][%d] getExampleHelloworldOK  %+v", 200, o.Payload)
}

func (o *GetExampleHelloworldOK) String() string {
	return fmt.Sprintf("[GET /example/helloworld][%d] getExampleHelloworldOK  %+v", 200, o.Payload)
}

func (o *GetExampleHelloworldOK) GetPayload() string {
	return o.Payload
}

func (o *GetExampleHelloworldOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
