// Code generated by go-swagger; DO NOT EDIT.

package page

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetPageAdminParams creates a new GetPageAdminParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetPageAdminParams() *GetPageAdminParams {
	return &GetPageAdminParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetPageAdminParamsWithTimeout creates a new GetPageAdminParams object
// with the ability to set a timeout on a request.
func NewGetPageAdminParamsWithTimeout(timeout time.Duration) *GetPageAdminParams {
	return &GetPageAdminParams{
		timeout: timeout,
	}
}

// NewGetPageAdminParamsWithContext creates a new GetPageAdminParams object
// with the ability to set a context for a request.
func NewGetPageAdminParamsWithContext(ctx context.Context) *GetPageAdminParams {
	return &GetPageAdminParams{
		Context: ctx,
	}
}

// NewGetPageAdminParamsWithHTTPClient creates a new GetPageAdminParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetPageAdminParamsWithHTTPClient(client *http.Client) *GetPageAdminParams {
	return &GetPageAdminParams{
		HTTPClient: client,
	}
}

/*
GetPageAdminParams contains all the parameters to send to the API endpoint

	for the get page admin operation.

	Typically these are written to a http.Request.
*/
type GetPageAdminParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get page admin params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetPageAdminParams) WithDefaults() *GetPageAdminParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get page admin params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetPageAdminParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get page admin params
func (o *GetPageAdminParams) WithTimeout(timeout time.Duration) *GetPageAdminParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get page admin params
func (o *GetPageAdminParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get page admin params
func (o *GetPageAdminParams) WithContext(ctx context.Context) *GetPageAdminParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get page admin params
func (o *GetPageAdminParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get page admin params
func (o *GetPageAdminParams) WithHTTPClient(client *http.Client) *GetPageAdminParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get page admin params
func (o *GetPageAdminParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetPageAdminParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
