// Code generated by go-swagger; DO NOT EDIT.

package page

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetAPIV1AuthSignUpParams creates a new GetAPIV1AuthSignUpParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetAPIV1AuthSignUpParams() *GetAPIV1AuthSignUpParams {
	return &GetAPIV1AuthSignUpParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetAPIV1AuthSignUpParamsWithTimeout creates a new GetAPIV1AuthSignUpParams object
// with the ability to set a timeout on a request.
func NewGetAPIV1AuthSignUpParamsWithTimeout(timeout time.Duration) *GetAPIV1AuthSignUpParams {
	return &GetAPIV1AuthSignUpParams{
		timeout: timeout,
	}
}

// NewGetAPIV1AuthSignUpParamsWithContext creates a new GetAPIV1AuthSignUpParams object
// with the ability to set a context for a request.
func NewGetAPIV1AuthSignUpParamsWithContext(ctx context.Context) *GetAPIV1AuthSignUpParams {
	return &GetAPIV1AuthSignUpParams{
		Context: ctx,
	}
}

// NewGetAPIV1AuthSignUpParamsWithHTTPClient creates a new GetAPIV1AuthSignUpParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetAPIV1AuthSignUpParamsWithHTTPClient(client *http.Client) *GetAPIV1AuthSignUpParams {
	return &GetAPIV1AuthSignUpParams{
		HTTPClient: client,
	}
}

/*
GetAPIV1AuthSignUpParams contains all the parameters to send to the API endpoint

	for the get API v1 auth sign up operation.

	Typically these are written to a http.Request.
*/
type GetAPIV1AuthSignUpParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get API v1 auth sign up params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAPIV1AuthSignUpParams) WithDefaults() *GetAPIV1AuthSignUpParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get API v1 auth sign up params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAPIV1AuthSignUpParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get API v1 auth sign up params
func (o *GetAPIV1AuthSignUpParams) WithTimeout(timeout time.Duration) *GetAPIV1AuthSignUpParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get API v1 auth sign up params
func (o *GetAPIV1AuthSignUpParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get API v1 auth sign up params
func (o *GetAPIV1AuthSignUpParams) WithContext(ctx context.Context) *GetAPIV1AuthSignUpParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get API v1 auth sign up params
func (o *GetAPIV1AuthSignUpParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get API v1 auth sign up params
func (o *GetAPIV1AuthSignUpParams) WithHTTPClient(client *http.Client) *GetAPIV1AuthSignUpParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get API v1 auth sign up params
func (o *GetAPIV1AuthSignUpParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetAPIV1AuthSignUpParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
