// Code generated by go-swagger; DO NOT EDIT.

package page

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetPageHomepageReader is a Reader for the GetPageHomepage structure.
type GetPageHomepageReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetPageHomepageReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 202:
		result := NewGetPageHomepageAccepted()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetPageHomepageBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewGetPageHomepageUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /page/homepage] GetPageHomepage", response, response.Code())
	}
}

// NewGetPageHomepageAccepted creates a GetPageHomepageAccepted with default headers values
func NewGetPageHomepageAccepted() *GetPageHomepageAccepted {
	return &GetPageHomepageAccepted{}
}

/*
GetPageHomepageAccepted describes a response with status code 202, with default header values.

Accepted
*/
type GetPageHomepageAccepted struct {
	Payload string
}

// IsSuccess returns true when this get page homepage accepted response has a 2xx status code
func (o *GetPageHomepageAccepted) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get page homepage accepted response has a 3xx status code
func (o *GetPageHomepageAccepted) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get page homepage accepted response has a 4xx status code
func (o *GetPageHomepageAccepted) IsClientError() bool {
	return false
}

// IsServerError returns true when this get page homepage accepted response has a 5xx status code
func (o *GetPageHomepageAccepted) IsServerError() bool {
	return false
}

// IsCode returns true when this get page homepage accepted response a status code equal to that given
func (o *GetPageHomepageAccepted) IsCode(code int) bool {
	return code == 202
}

// Code gets the status code for the get page homepage accepted response
func (o *GetPageHomepageAccepted) Code() int {
	return 202
}

func (o *GetPageHomepageAccepted) Error() string {
	return fmt.Sprintf("[GET /page/homepage][%d] getPageHomepageAccepted  %+v", 202, o.Payload)
}

func (o *GetPageHomepageAccepted) String() string {
	return fmt.Sprintf("[GET /page/homepage][%d] getPageHomepageAccepted  %+v", 202, o.Payload)
}

func (o *GetPageHomepageAccepted) GetPayload() string {
	return o.Payload
}

func (o *GetPageHomepageAccepted) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetPageHomepageBadRequest creates a GetPageHomepageBadRequest with default headers values
func NewGetPageHomepageBadRequest() *GetPageHomepageBadRequest {
	return &GetPageHomepageBadRequest{}
}

/*
GetPageHomepageBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type GetPageHomepageBadRequest struct {

	/* Authorization
	 */
	Authorization string

	Payload string
}

// IsSuccess returns true when this get page homepage bad request response has a 2xx status code
func (o *GetPageHomepageBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get page homepage bad request response has a 3xx status code
func (o *GetPageHomepageBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get page homepage bad request response has a 4xx status code
func (o *GetPageHomepageBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this get page homepage bad request response has a 5xx status code
func (o *GetPageHomepageBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this get page homepage bad request response a status code equal to that given
func (o *GetPageHomepageBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the get page homepage bad request response
func (o *GetPageHomepageBadRequest) Code() int {
	return 400
}

func (o *GetPageHomepageBadRequest) Error() string {
	return fmt.Sprintf("[GET /page/homepage][%d] getPageHomepageBadRequest  %+v", 400, o.Payload)
}

func (o *GetPageHomepageBadRequest) String() string {
	return fmt.Sprintf("[GET /page/homepage][%d] getPageHomepageBadRequest  %+v", 400, o.Payload)
}

func (o *GetPageHomepageBadRequest) GetPayload() string {
	return o.Payload
}

func (o *GetPageHomepageBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header Authorization
	hdrAuthorization := response.GetHeader("Authorization")

	if hdrAuthorization != "" {
		o.Authorization = hdrAuthorization
	}

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetPageHomepageUnauthorized creates a GetPageHomepageUnauthorized with default headers values
func NewGetPageHomepageUnauthorized() *GetPageHomepageUnauthorized {
	return &GetPageHomepageUnauthorized{}
}

/*
GetPageHomepageUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type GetPageHomepageUnauthorized struct {
	Payload string
}

// IsSuccess returns true when this get page homepage unauthorized response has a 2xx status code
func (o *GetPageHomepageUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get page homepage unauthorized response has a 3xx status code
func (o *GetPageHomepageUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get page homepage unauthorized response has a 4xx status code
func (o *GetPageHomepageUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this get page homepage unauthorized response has a 5xx status code
func (o *GetPageHomepageUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this get page homepage unauthorized response a status code equal to that given
func (o *GetPageHomepageUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the get page homepage unauthorized response
func (o *GetPageHomepageUnauthorized) Code() int {
	return 401
}

func (o *GetPageHomepageUnauthorized) Error() string {
	return fmt.Sprintf("[GET /page/homepage][%d] getPageHomepageUnauthorized  %+v", 401, o.Payload)
}

func (o *GetPageHomepageUnauthorized) String() string {
	return fmt.Sprintf("[GET /page/homepage][%d] getPageHomepageUnauthorized  %+v", 401, o.Payload)
}

func (o *GetPageHomepageUnauthorized) GetPayload() string {
	return o.Payload
}

func (o *GetPageHomepageUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
