// Code generated by go-swagger; DO NOT EDIT.

package auth

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetAuthSignUpParams creates a new GetAuthSignUpParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetAuthSignUpParams() *GetAuthSignUpParams {
	return &GetAuthSignUpParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetAuthSignUpParamsWithTimeout creates a new GetAuthSignUpParams object
// with the ability to set a timeout on a request.
func NewGetAuthSignUpParamsWithTimeout(timeout time.Duration) *GetAuthSignUpParams {
	return &GetAuthSignUpParams{
		timeout: timeout,
	}
}

// NewGetAuthSignUpParamsWithContext creates a new GetAuthSignUpParams object
// with the ability to set a context for a request.
func NewGetAuthSignUpParamsWithContext(ctx context.Context) *GetAuthSignUpParams {
	return &GetAuthSignUpParams{
		Context: ctx,
	}
}

// NewGetAuthSignUpParamsWithHTTPClient creates a new GetAuthSignUpParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetAuthSignUpParamsWithHTTPClient(client *http.Client) *GetAuthSignUpParams {
	return &GetAuthSignUpParams{
		HTTPClient: client,
	}
}

/*
GetAuthSignUpParams contains all the parameters to send to the API endpoint

	for the get auth sign up operation.

	Typically these are written to a http.Request.
*/
type GetAuthSignUpParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get auth sign up params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAuthSignUpParams) WithDefaults() *GetAuthSignUpParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get auth sign up params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAuthSignUpParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get auth sign up params
func (o *GetAuthSignUpParams) WithTimeout(timeout time.Duration) *GetAuthSignUpParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get auth sign up params
func (o *GetAuthSignUpParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get auth sign up params
func (o *GetAuthSignUpParams) WithContext(ctx context.Context) *GetAuthSignUpParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get auth sign up params
func (o *GetAuthSignUpParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get auth sign up params
func (o *GetAuthSignUpParams) WithHTTPClient(client *http.Client) *GetAuthSignUpParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get auth sign up params
func (o *GetAuthSignUpParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetAuthSignUpParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
