// Code generated by go-swagger; DO NOT EDIT.

package auth

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// PostAuthLogoutFormReader is a Reader for the PostAuthLogoutForm structure.
type PostAuthLogoutFormReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostAuthLogoutFormReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostAuthLogoutFormOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[POST /auth/logout-form] PostAuthLogoutForm", response, response.Code())
	}
}

// NewPostAuthLogoutFormOK creates a PostAuthLogoutFormOK with default headers values
func NewPostAuthLogoutFormOK() *PostAuthLogoutFormOK {
	return &PostAuthLogoutFormOK{}
}

/*
PostAuthLogoutFormOK describes a response with status code 200, with default header values.

success
*/
type PostAuthLogoutFormOK struct {
	Payload string
}

// IsSuccess returns true when this post auth logout form o k response has a 2xx status code
func (o *PostAuthLogoutFormOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post auth logout form o k response has a 3xx status code
func (o *PostAuthLogoutFormOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post auth logout form o k response has a 4xx status code
func (o *PostAuthLogoutFormOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this post auth logout form o k response has a 5xx status code
func (o *PostAuthLogoutFormOK) IsServerError() bool {
	return false
}

// IsCode returns true when this post auth logout form o k response a status code equal to that given
func (o *PostAuthLogoutFormOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the post auth logout form o k response
func (o *PostAuthLogoutFormOK) Code() int {
	return 200
}

func (o *PostAuthLogoutFormOK) Error() string {
	return fmt.Sprintf("[POST /auth/logout-form][%d] postAuthLogoutFormOK  %+v", 200, o.Payload)
}

func (o *PostAuthLogoutFormOK) String() string {
	return fmt.Sprintf("[POST /auth/logout-form][%d] postAuthLogoutFormOK  %+v", 200, o.Payload)
}

func (o *PostAuthLogoutFormOK) GetPayload() string {
	return o.Payload
}

func (o *PostAuthLogoutFormOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
