// Code generated by go-swagger; DO NOT EDIT.

package auth

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"AdminPanelCorp/docs/output_swag/models"
)

// NewPostAuthRegistrationFormParams creates a new PostAuthRegistrationFormParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostAuthRegistrationFormParams() *PostAuthRegistrationFormParams {
	return &PostAuthRegistrationFormParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostAuthRegistrationFormParamsWithTimeout creates a new PostAuthRegistrationFormParams object
// with the ability to set a timeout on a request.
func NewPostAuthRegistrationFormParamsWithTimeout(timeout time.Duration) *PostAuthRegistrationFormParams {
	return &PostAuthRegistrationFormParams{
		timeout: timeout,
	}
}

// NewPostAuthRegistrationFormParamsWithContext creates a new PostAuthRegistrationFormParams object
// with the ability to set a context for a request.
func NewPostAuthRegistrationFormParamsWithContext(ctx context.Context) *PostAuthRegistrationFormParams {
	return &PostAuthRegistrationFormParams{
		Context: ctx,
	}
}

// NewPostAuthRegistrationFormParamsWithHTTPClient creates a new PostAuthRegistrationFormParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostAuthRegistrationFormParamsWithHTTPClient(client *http.Client) *PostAuthRegistrationFormParams {
	return &PostAuthRegistrationFormParams{
		HTTPClient: client,
	}
}

/*
PostAuthRegistrationFormParams contains all the parameters to send to the API endpoint

	for the post auth registration form operation.

	Typically these are written to a http.Request.
*/
type PostAuthRegistrationFormParams struct {

	/* Input.

	   account info
	*/
	Input []*models.ModelsRegisterUser

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post auth registration form params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAuthRegistrationFormParams) WithDefaults() *PostAuthRegistrationFormParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post auth registration form params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAuthRegistrationFormParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post auth registration form params
func (o *PostAuthRegistrationFormParams) WithTimeout(timeout time.Duration) *PostAuthRegistrationFormParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post auth registration form params
func (o *PostAuthRegistrationFormParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post auth registration form params
func (o *PostAuthRegistrationFormParams) WithContext(ctx context.Context) *PostAuthRegistrationFormParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post auth registration form params
func (o *PostAuthRegistrationFormParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post auth registration form params
func (o *PostAuthRegistrationFormParams) WithHTTPClient(client *http.Client) *PostAuthRegistrationFormParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post auth registration form params
func (o *PostAuthRegistrationFormParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithInput adds the input to the post auth registration form params
func (o *PostAuthRegistrationFormParams) WithInput(input []*models.ModelsRegisterUser) *PostAuthRegistrationFormParams {
	o.SetInput(input)
	return o
}

// SetInput adds the input to the post auth registration form params
func (o *PostAuthRegistrationFormParams) SetInput(input []*models.ModelsRegisterUser) {
	o.Input = input
}

// WriteToRequest writes these params to a swagger request
func (o *PostAuthRegistrationFormParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Input != nil {
		if err := r.SetBodyParam(o.Input); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
