// Code generated by go-swagger; DO NOT EDIT.

package auth

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPostAuthLogoutFormParams creates a new PostAuthLogoutFormParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostAuthLogoutFormParams() *PostAuthLogoutFormParams {
	return &PostAuthLogoutFormParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostAuthLogoutFormParamsWithTimeout creates a new PostAuthLogoutFormParams object
// with the ability to set a timeout on a request.
func NewPostAuthLogoutFormParamsWithTimeout(timeout time.Duration) *PostAuthLogoutFormParams {
	return &PostAuthLogoutFormParams{
		timeout: timeout,
	}
}

// NewPostAuthLogoutFormParamsWithContext creates a new PostAuthLogoutFormParams object
// with the ability to set a context for a request.
func NewPostAuthLogoutFormParamsWithContext(ctx context.Context) *PostAuthLogoutFormParams {
	return &PostAuthLogoutFormParams{
		Context: ctx,
	}
}

// NewPostAuthLogoutFormParamsWithHTTPClient creates a new PostAuthLogoutFormParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostAuthLogoutFormParamsWithHTTPClient(client *http.Client) *PostAuthLogoutFormParams {
	return &PostAuthLogoutFormParams{
		HTTPClient: client,
	}
}

/*
PostAuthLogoutFormParams contains all the parameters to send to the API endpoint

	for the post auth logout form operation.

	Typically these are written to a http.Request.
*/
type PostAuthLogoutFormParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post auth logout form params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAuthLogoutFormParams) WithDefaults() *PostAuthLogoutFormParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post auth logout form params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAuthLogoutFormParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post auth logout form params
func (o *PostAuthLogoutFormParams) WithTimeout(timeout time.Duration) *PostAuthLogoutFormParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post auth logout form params
func (o *PostAuthLogoutFormParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post auth logout form params
func (o *PostAuthLogoutFormParams) WithContext(ctx context.Context) *PostAuthLogoutFormParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post auth logout form params
func (o *PostAuthLogoutFormParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post auth logout form params
func (o *PostAuthLogoutFormParams) WithHTTPClient(client *http.Client) *PostAuthLogoutFormParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post auth logout form params
func (o *PostAuthLogoutFormParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *PostAuthLogoutFormParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
