// Code generated by go-swagger; DO NOT EDIT.

package auth

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"AdminPanelCorp/docs/output_swag/models"
)

// NewPostAuthLoginFormParams creates a new PostAuthLoginFormParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostAuthLoginFormParams() *PostAuthLoginFormParams {
	return &PostAuthLoginFormParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostAuthLoginFormParamsWithTimeout creates a new PostAuthLoginFormParams object
// with the ability to set a timeout on a request.
func NewPostAuthLoginFormParamsWithTimeout(timeout time.Duration) *PostAuthLoginFormParams {
	return &PostAuthLoginFormParams{
		timeout: timeout,
	}
}

// NewPostAuthLoginFormParamsWithContext creates a new PostAuthLoginFormParams object
// with the ability to set a context for a request.
func NewPostAuthLoginFormParamsWithContext(ctx context.Context) *PostAuthLoginFormParams {
	return &PostAuthLoginFormParams{
		Context: ctx,
	}
}

// NewPostAuthLoginFormParamsWithHTTPClient creates a new PostAuthLoginFormParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostAuthLoginFormParamsWithHTTPClient(client *http.Client) *PostAuthLoginFormParams {
	return &PostAuthLoginFormParams{
		HTTPClient: client,
	}
}

/*
PostAuthLoginFormParams contains all the parameters to send to the API endpoint

	for the post auth login form operation.

	Typically these are written to a http.Request.
*/
type PostAuthLoginFormParams struct {

	/* Input.

	   account info
	*/
	Input *models.ModelsUser

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post auth login form params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAuthLoginFormParams) WithDefaults() *PostAuthLoginFormParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post auth login form params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAuthLoginFormParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post auth login form params
func (o *PostAuthLoginFormParams) WithTimeout(timeout time.Duration) *PostAuthLoginFormParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post auth login form params
func (o *PostAuthLoginFormParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post auth login form params
func (o *PostAuthLoginFormParams) WithContext(ctx context.Context) *PostAuthLoginFormParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post auth login form params
func (o *PostAuthLoginFormParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post auth login form params
func (o *PostAuthLoginFormParams) WithHTTPClient(client *http.Client) *PostAuthLoginFormParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post auth login form params
func (o *PostAuthLoginFormParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithInput adds the input to the post auth login form params
func (o *PostAuthLoginFormParams) WithInput(input *models.ModelsUser) *PostAuthLoginFormParams {
	o.SetInput(input)
	return o
}

// SetInput adds the input to the post auth login form params
func (o *PostAuthLoginFormParams) SetInput(input *models.ModelsUser) {
	o.Input = input
}

// WriteToRequest writes these params to a swagger request
func (o *PostAuthLoginFormParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Input != nil {
		if err := r.SetBodyParam(o.Input); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
