// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ModelsRegisterUser models register user
//
// swagger:model models.RegisterUser
type ModelsRegisterUser struct {

	// email
	Email string `json:"email,omitempty"`

	// username
	Username string `json:"username,omitempty"`
}

// Validate validates this models register user
func (m *ModelsRegisterUser) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this models register user based on context it is used
func (m *ModelsRegisterUser) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ModelsRegisterUser) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ModelsRegisterUser) UnmarshalBinary(b []byte) error {
	var res ModelsRegisterUser
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
